name: Build Windows binaries

on:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.0'

      - name: Create directories
        run: |
          mkdir -p build

      - name: Install pyinstaller
        working-directory: build
        run: |
          pip install pyinstaller==5.5

      - name: Build backup executable with pyinstaller
        working-directory: build
        run: pyinstaller --onefile --name backup ../backup.py

      - name: Upload backup.exe
        uses: actions/upload-artifact@v4
        with:
          name: backup
          path: build/dist/backup.exe